### ISSUE TITLE
Emergency

### ISSUE THREAD

**Issue by AntoineDubois** [alanmarietta/GPTtrading#1]
Alanmarietta
Your project is public. I can see your API ID and Secret keys !
` std::string responseString;
std::string url = "https://data.alpaca.markets/v1/last/stocks/" + symbol;
curl_easy_setopt(curl, CURLOPT_URL, url.c_str());

struct curl_slist *headers = NULL;
headers = curl_slist_append(headers, "APCA-API-KEY-ID: PKO3RZBLQ0QU5NSTGBDY");
headers = curl_slist_append(headers, "APCA-API-SECRET-KEY: YpvjSz8Z34IEpdu8MZ1BdGUAPDOfqan7VmKmQqyV");
curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
curl_easy_setopt(curl, CURLOPT_WRITEDATA, &responseString);
`
😉

**Comment by alanmarietta** [comment]
Thanks! All fixed.
